vscode:
  extensions:
    - pmneo.tsimporter@2.0.1:LI0jZxdaZNXYOYbOWaaIvA==
    - xabikos.JavaScriptSnippets@1.7.2:XXmiw8r7K3Guifex/E73aQ==
    - ecmel.vscode-html-css@0.2.3:RBTpzQbz8rn5KTlc82tnsQ==
    - lonefy.vscode-JS-CSS-HTML-formatter@0.2.3:0KRPksz5Vs5AlhZ+PiwG9w==
    - vscode-icons-team.vscode-icons@9.4.0:p8v1cdsvp6vMqnyZC/C3hQ==
    - quicktype.quicktype@12.0.46:f45bY/ldS1sS4TJ6ZLBsxA==
    - esbenp.prettier-vscode@2.3.0:1F0Pvb/ORZ/T+b60LIMs8w==